theme: minima

title: Ronan Cummins
description: "Researcher and AI leader specialising in Natural Language Processing, Machine Learning, and Information Retrieval."

author:
  name: Ronan Cummins
  email: ronan.cummins@cl.cam.ac.uk

github_username: ronancummins
linkedin_username: ronan-cummins-b046997
